dist: xenial
language: python
python:
- '3.7'
install:
- pip install -U -r requirements.txt
- pip install -U -r test-requirements.txt
script:
- flake8 .
- coverage run --source api/ -m pytest --verbose tests/unit/ && coverage report
